# Default configuration for Dual Momentum Strategy

# Momentum calculation period (trading days)
# Standard is 252 days (1 year), but can be adjusted
lookback_period: 252

# How often to rebalance the portfolio
# Options: 'daily', 'weekly', 'monthly', 'quarterly', 'yearly'
rebalance_frequency: monthly

# Number of top-ranked assets to hold
# Standard dual momentum uses 1, but can hold multiple
position_count: 1

# Absolute momentum threshold
# Only invest in assets with momentum > threshold
# 0.0 means only positive momentum assets
absolute_threshold: 0.0

# Use volatility-adjusted momentum scores
# Divides raw momentum by volatility for risk-adjusted ranking
use_volatility_adjustment: false

# Safe asset to hold when all risky assets fail absolute momentum filter
# Common choices: 'SHY' (short-term bonds), 'AGG' (aggregate bonds), 'BIL' (T-bills)
safe_asset: SHY

# Minimum signal strength to generate trade
# Range: 0.0 to 1.0
signal_threshold: 0.0

# === Signal Strength Calculation ===
# Method for calculating signal strength (how to weight assets)
# Options:
#   'binary': All passing assets get equal weight (strength=1.0)
#             Best for: Simple equal-weight strategies
#             Example: If SPY has 10% momentum and QQQ has 20%, both get strength=1.0
#
#   'linear': Linear scaling from threshold to threshold + scale_range
#             Best for: Gradually increasing position size with momentum
#             Example: With threshold=0.0 and scale_range=0.1:
#                      5% momentum → 0.5 strength, 10% momentum → 1.0 strength
#
#   'proportional': Weight proportional to momentum magnitude
#             Best for: Allocating more to higher momentum assets
#             Example: SPY (10% mom) gets 33% weight, QQQ (20% mom) gets 67% weight
#
#   'momentum_ratio': Normalize by highest momentum asset
#             Best for: Emphasizing the leader while keeping others
#             Example: SPY (10% mom) → 0.5, QQQ (20% mom) → 1.0
#
strength_method: binary

# Scale range for 'linear' method (ignored for other methods)
# Momentum must exceed threshold by this amount to reach full strength
# Example: With threshold=0.0 and scale_range=0.1:
#   - 0% momentum → 0.0 strength (filtered out by threshold)
#   - 5% momentum → 0.5 strength
#   - 10%+ momentum → 1.0 strength
strength_scale_range: 0.10

# Asset universe for the strategy
# Leave empty or null to use all available assets
universe:
  - SPY   # S&P 500
  - EFA   # International Developed Markets
  - EEM   # Emerging Markets
  - AGG   # U.S. Aggregate Bonds
  - TLT   # Long-term Treasuries
  - GLD   # Gold
  - DBC   # Commodities
