# Railway Environment Variables Configuration
# ============================================
#
# IMPORTANT: This application reads API keys from RAILWAY ENVIRONMENT VARIABLES.
# 
# This secrets.toml file is NOT used on Railway deployments.
# It exists only to prevent Streamlit errors when running locally.
#
# FOR RAILWAY DEPLOYMENT:
# -----------------------
# Configure API keys in Railway Dashboard → Variables:
#   - ALPHAVANTAGE_API_KEY (optional)
#   - TWELVEDATA_API_KEY (optional)
#
# Railway automatically injects these as environment variables that the app reads.
#
# API KEYS ARE OPTIONAL:
# ----------------------
# The system works perfectly with just Yahoo Finance (no API keys needed).
# Alpha Vantage and Twelve Data provide backup data sources if Yahoo fails.
#
# HOW TO GET FREE API KEYS (OPTIONAL):
# ------------------------------------
# Alpha Vantage: https://www.alphavantage.co/support/#api-key
#   - Free tier: 500 requests/day, 5 requests/minute
#
# Twelve Data: https://twelvedata.com/pricing
#   - Free tier: 800 requests/day, 8 requests/minute
#
# RAILWAY SETUP:
# --------------
# 1. Go to Railway Dashboard → Your Project → Variables
# 2. Click "New Variable"
# 3. Add (optional):
#    - Variable: ALPHAVANTAGE_API_KEY
#      Value: your_actual_api_key_here
#    - Variable: TWELVEDATA_API_KEY
#      Value: your_actual_api_key_here
# 4. Railway will automatically inject these as environment variables
# 5. The app will automatically detect and use them
#
# NO CONFIGURATION NEEDED IN THIS FILE FOR RAILWAY DEPLOYMENT!
