# Streamlit Secrets Configuration
# ================================
#
# This file contains optional API keys for alternative data sources.
# These are NOT required for backtesting - the system works fine with just Yahoo Finance.
#
# Alpha Vantage and Twelve Data are backup data sources that provide automatic
# failover if Yahoo Finance is unavailable.
#
# DEPLOYMENT NOTE:
# ----------------
# For cloud deployments (Railway, Streamlit Cloud, etc.), it's recommended to use
# environment variables instead of this file:
#   - ALPHAVANTAGE_API_KEY
#   - TWELVEDATA_API_KEY
#
# HOW TO GET FREE API KEYS (OPTIONAL):
# ------------------------------------
# Alpha Vantage: https://www.alphavantage.co/support/#api-key
#   - Free tier: 500 requests/day, 5 requests/minute
#
# Twelve Data: https://twelvedata.com/pricing
#   - Free tier: 800 requests/day, 8 requests/minute
#
# CONFIGURATION:
# --------------
# Uncomment and add your API keys below if you want to enable backup data sources.
# If you don't have API keys or don't want to use them, leave this file as-is.
# The system will work perfectly fine using only Yahoo Finance.

# Optional: Alpha Vantage API Key for backup data source
# ALPHAVANTAGE_API_KEY = "your_alphavantage_api_key_here"

# Optional: Twelve Data API Key for backup data source  
# TWELVEDATA_API_KEY = "your_twelvedata_api_key_here"

# NOTE: If these keys are not configured, the system will:
# 1. Use Yahoo Finance as the primary (and only) data source
# 2. Still work perfectly for all backtesting operations
# 3. Not display any errors or warnings
